### ISSUE TITLE
草..现在搞得很很卡,ScrollVIew都滚得好垃圾

### ISSUE THREAD

**Issue by xiaotiekeng** [wechat-miniprogram/minigame-canvas-engine#1]
现在还是不行..还需要优化..擦..2小时前更新..然后我新更新你的代码才不会报错..问题太多了..搞得还是不行...

**Comment by xiaotiekeng** [comment]
Scroll View滚得像狗屎一样..哎..

**Comment by yuanzm** [comment]
额，理性提Issue，卡是怎么个卡，有没有示例代码之类的，可以现在PlayGround运行，然后贴下示例代码：https://wechat-miniprogram.github.io/minigame-canvas-engine/

**Comment by edgexie** [comment]
首先感谢作者贡献，请问这个滚动支持惯性么？

**Comment by yuanzm** [comment]
> 首先感谢作者贡献，请问这个滚动支持惯性么？

csslayout分支是webgl版本，那里的滚动经切换成支持惯性的了，Webgl的性能也会好很多，方便加个联系方式么？

**Comment by yuanzm** [comment]
这两天我抽个时间将canvas 2d版本的滚动改造下，现在的版本滚动确实没做好，新版本会切到开源的Scroller组件，横向滚动纵向滚动都可以支持，橡皮筋效果也可以支持。

**Comment by edgexie** [comment]
> > 首先感谢作者贡献，请问这个滚动支持惯性么？
> 
> csslayout分支是webgl版本，那里的滚动经切换成支持惯性的了，Webgl的性能也会好很多，方便加个联系方式么？

我是被cocos 推荐用到这个引擎的。就是滚动很太难受了。加我微信吧 `oo0Opt`  (小写oo 数字0 大写O )。

**Comment by xiaotiekeng** [comment]
我不搞小游戏多年了....挣不到钱..快餐费都挣不到.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月17日(星期四) 中午11:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wechat-miniprogram/minigame-canvas-engine] 草..现在搞得很很卡,ScrollVIew都滚得好垃圾 (#1)





   
首先感谢作者贡献，请问这个滚动支持惯性么？
  
csslayout分支是webgl版本，那里的滚动经切换成支持惯性的了，Webgl的性能也会好很多，方便加个联系方式么？
  
我是被cocos 推荐用到这个引擎的。就是滚动很太难受了。加我微信吧 oo0Opt  (小写oo 数字0 大写O )。

**Comment by edgexie** [comment]
@xiaotiekeng 我想的是把游戏技术用到工业监控里，比如现在流行的数字孪生。 目前我还没找到突破口。
