### ISSUE TITLE
Github 与 Npm 的版本对应

### ISSUE THREAD

**Issue by chenmnkken** [wechat-miniprogram/minigame-canvas-engine#11]
请问下作者，该项目的 Github Master 分支已经是 1.0.6，而且我看 Github 也在频繁更新，但是 Npm 包已经好久没有更新过了，是有特定的分支与 Npm 包对应吗，请问该项目的更新策略是怎样的呢？

**Comment by yuanzm** [comment]
可以问下你的使用场景么，因为最近的迭代都是针对小游戏场景来迭代，所以小游戏插件都会实时更新最新的，npm按理也要最新的，但上次发布的时候代理有一定的问题就没有同步到npm

**Comment by chenmnkken** [comment]
我的业务场景比较复杂，可能会涉及到不少 engine 的改造完善。

**Comment by yuanzm** [comment]
额，可以加个联系方式沟通下么，如果改造完善的话，不妨一起来共建这个项目

**Comment by chenmnkken** [comment]
回头我给你发邮件。

**Comment by yuanzm** [comment]
已同步
