### ISSUE TITLE
通过微信引擎插件的方式引用到游戏中，只要版本超过0.08就无法上传代码，能否帮忙看一下是什么问题？

### ISSUE THREAD

**Issue by kylin1011lu** [wechat-miniprogram/minigame-canvas-engine#14]
![问题反馈](https://user-images.githubusercontent.com/9585940/149459398-88d28a86-d218-4f27-ac75-214480d1c61e.jpg)
![问题反馈2](https://user-images.githubusercontent.com/9585940/149459505-bf75b081-3d72-44ff-af3e-7bcd2f06f439.jpg)

**Comment by yuanzm** [comment]
用"latest"试试呢？

**Comment by yuanzm** [comment]
0.0.9主要是更新bitmap相关的，0.0.10支持了dataset，没有相关需求用0.0.8即可

**Comment by kylin1011lu** [comment]
0.08版本也是一样问题，通过引擎插件方式引入，会无法上传代码。只有0.07版本正常，但是0.07版本目前游戏内点击事件会失效，无法使用。目前只能把插件代码放到工程里面才能升级。但是这样会占用包体大小。

**Comment by yuanzm** [comment]
好，我拉开发者工具的同事看看

**Comment by yuanzm** [comment]
重新发布下好了，最新的用0.0.11

**Comment by kylin1011lu** [comment]
可以了。谢谢
