### ISSUE TITLE
插件在微信小游戏那边添加后，如何移除，网页地址状态一直都是已添加

### ISSUE THREAD

**Issue by jsroads** [wechat-miniprogram/minigame-canvas-engine#16]
添加教程 https://wechat-miniprogram.github.io/minigame-canvas-engine/#%E5%BE%AE%E4%BF%A1%E5%B0%8F%E6%B8%B8%E6%88%8F%E6%8F%92%E4%BB%B6
下面的这个网页 一直是已添加 无法取消
https://mp.weixin.qq.com/wxopen/plugindevdoc?appid=wx7a727ff7d940bb3f&token=&lang=zh_CN#-

请问一下 如何取消这个 插件呢？一直没找到 设置的地方 也没有客服和邮箱联系

**Comment by yuanzm** [comment]
game.json不引用则没有影响

**Comment by jsroads** [comment]
好的，谢谢，没有影响就好
