### ISSUE TITLE
是否可以支持显示富文本内容

### ISSUE THREAD

**Issue by liangshen001** [wechat-miniprogram/minigame-canvas-engine#19]
如题, 是否可以提供富文本标签来实现
`<richtext value="xxx"></richtext>`

**Comment by yuanzm** [comment]
什么场景想要富文本？

**Comment by liangshen001** [comment]
使用这种方式来做游戏的公告, 公告的内容会是一个富文本内容比如
```
<h1>图文</h1>
<p><span style="color:#ff0000">测试内容</span></p>
```
类似这种的

**Comment by yuanzm** [comment]
留个联系方式吧，交流下这个需求

**Comment by liangshen001** [comment]
可以加我Q: 850598163

**Comment by yuanzm** [comment]
加了，麻烦通过下

**Comment by yuanzm** [comment]
已经支持并且正式发布，可参考文档：https://wechat-miniprogram.github.io/minigame-canvas-engine/plugin/richtext.html
