### ISSUE TITLE
只做离屏，对主屏2d或者webgl同时兼容？

### ISSUE THREAD

**Issue by heshule** [wechat-miniprogram/minigame-canvas-engine#2]
大大，请问如果用你这套框架做2d离屏，是否能够在自动兼容webgl的主屏上渲染？

**Comment by yuanzm** [comment]
可以的，我写了一个demo： https://github.com/wechat-miniprogram/minigame-canvas-engine/tree/master/demos/webgl

主屏是webgl，2d离屏画了个排行榜，通过纹理的形式渲染到主屏。
