### ISSUE TITLE
scrollview不支持透明背景效果 即backgroundColor属性设置为transparent无效

### ISSUE THREAD

**Issue by liangshen001** [wechat-miniprogram/minigame-canvas-engine#20]
需要使用canvas引擎来写一个页面, 页面有一张背景图, 需要在背景图上写一个滚动条, 发现滚动条不能实现透明效果会挡住背景图
如下图所示

![Screenshot 2023-05-10 at 15 37 31](https://github.com/wechat-miniprogram/minigame-canvas-engine/assets/22604816/79da38c2-f403-4a9a-8fb2-69c66cec20c3)

[问题代码](https://codepen.io/liangshen/pen/YzJadmZ)

请问我该如何实现预期的效果.

**Comment by yuanzm** [comment]
应该是个bug，我来看看

**Comment by yuanzm** [comment]
确实有这个问题，原因在于ScrollView跟下面的内容是公用一个canvas，scrollview在执行滚动擦除的时候，其实内容已经透到最下面去了，看不到背景图的，我来修改下。

**Comment by liangshen001** [comment]
另外npm库是否考虑添加ts类型, 这样使用直接更直观

**Comment by yuanzm** [comment]
修复了，codepen不要写死 版本号引用即可：
import Layout from "https://cdn.skypack.dev/minigame-canvas-engine";

**Comment by yuanzm** [comment]
ts这个是该考虑考虑了，最开始写的时候ts还不够火

**Comment by liangshen001** [comment]
感谢🙏
