### ISSUE TITLE
目前能设置图片的z-index吗？

### ISSUE THREAD

**Issue by sarii0504** [wechat-miniprogram/minigame-canvas-engine#3]
用来做微信小游戏的开放域，实现过程中发现图片的堆叠顺序可能是根据图片渲染完成的先后决定的，这就导致了背景图片可能遮盖前景图片和文字，想请问一下是否能够设置图片的z-index属性呢？

**Comment by yuanzm** [comment]
暂时不支持，可以支持，可以用代码表明更具体一点的场景么？

**Comment by sarii0504** [comment]
目前已经找到替代的解决方案了。不过还是感谢回复！
场景如下，listItemBg是背景图，Icon是其上的Icon图，背景图可能会覆盖掉Icon                    
<image class="listItemBg" src="resources/bg.png"></image>
<image class ="listItemGradeIcon" src = "resources/grade.png"></image>
不知这样描述清楚了吗？ 
顺便再请问一下，引擎是否支持音效以及按钮的悬浮、点击等不同状态。

**Comment by yuanzm** [comment]
ok，这两点我下周末之前都支持下：
1. 支持index
2. 按钮的点击态度

不过音效是什么情况？我这属于渲染引擎，和音效无关诶

**Comment by yuanzm** [comment]
这里不需要支持zIndex，最新版已经修复了渲染层级问题，另外点击态的话，可以用下面的方式来实现
```
const title = Layout.getElementsById('title')[0]

    title.on('touchstart', (e) => {
        title.style.backgroundColor = '#444444';
       	Layout.repaint()
    })
   title.on('touchend', (e) => {
        title.style.backgroundColor = '#ffffff';
       	Layout.repaint()
    })
```
