### ISSUE TITLE
想知道文本可以像H5那样实现描边效果吗

### ISSUE THREAD

**Issue by Difficulty-in-naming** [wechat-miniprogram/minigame-canvas-engine#36]

**Comment by yuanzm** [comment]
截个图具体一点？主要是bitmaptet 好像也能解决这个需求

**Comment by yuanzm** [comment]
已经支持：https://wechat-miniprogram.github.io/minigame-canvas-engine/components/overview.html#%E6%A0%B7%E5%BC%8F
