### ISSUE TITLE
setfrienduserstorage: size of value exceed

### ISSUE THREAD

**Issue by ifengzp** [wechat-miniprogram/minigame-canvas-engine#4]
我参考interactivedemo里面实现好友互动赠送的逻辑，我发现里面有句注释：

// 用户每天只能给同一个好友赠送一次金币,每天最多送5次

但是整个checkInteractiveData.js文件的上下文里面并没有次数的比较，所以这句注释让我觉得有点摸不着头脑，然后我在真机测试的时候，jsserver抛出错误`setfrienduserstorage: size of value exceed`

我想问，这个5次是微信的强制性校验吗，不需要我们写相关的逻辑的，如果是，那我们在开发阶段真机调试的时候超过了5次怎么办？以及如何解决jsserver抛出错误`setfrienduserstorage: size of value exceed`这个问题

**Comment by yuanzm** [comment]
// 用户每天只能给同一个好友赠送一次金币,每天最多送5次
这个应该是注释没有删掉，默认不会有这个逻辑

setfrienduserstorage: size of value exceed可以检查下是不是设置的数据超过了1k

**Comment by ifengzp** [comment]
👌，问题已排查
